{"uuid":"562d09e6-01ef-4e05-9193-83dab6dcb60c","historyId":"241e703c357b89ae496fe6830d050b75","testCaseId":"38f8487e8cba94211cc90e2728f56f7f","fullName":"src/test/resources/Feature files/Array.feature:48","labels":[{"name":"tag","value":"Array"},{"name":"tag","value":"DsAlgo"},{"name":"tag","value":"ArrayPythonTryEditorFunc"},{"name":"host","value":"MyGenie"},{"name":"thread","value":"32536@MyGenie.TestNG-PoolService-9(49)"},{"name":"feature","value":"Array Module"},{"name":"story","value":"Arrays in Python TryEditor Functionality"},{"name":"suite","value":"Array Module"},{"name":"testClass","value":"Arrays in Python TryEditor Functionality"},{"name":"framework","value":"cucumber4jvm"},{"name":"language","value":"java"},{"name":"gherkin_uri","value":"file:///C:/Users/madhu/OneDrive/Desktop/SDET/AS_BDD/src/test/resources/Feature%20files/Array.feature"},{"name":"package","value":"src.test.resources.Feature files.Array_feature.Array Module"}],"links":[],"name":"Arrays in Python TryEditor Functionality","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Error initializing Excel data: Fail to save: an error occurs while saving the package : The part /xl/worksheets/sheet3.xml failed to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@6645db66. Enable logging via Log4j 2 for more details.","trace":"java.lang.RuntimeException: Error initializing Excel data: Fail to save: an error occurs while saving the package : The part /xl/worksheets/sheet3.xml failed to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@6645db66. Enable logging via Log4j 2 for more details.\r\n\tat appHook.Hooks.setUp(Hooks.java:35)\r\n"},"stage":"finished","steps":[{"name":"Given The user logged in to dsAlgo Portal and should be in Array Page","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1734654898685,"stop":1734654898686},{"name":"Given The user is on the Try Editor of Arrays in Python page","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1734654898691,"stop":1734654898692},{"name":"When The user enters the Invalid code2 in Text Editor and clicks RUN button","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1734654898694,"stop":1734654898694},{"name":"Then The syntaxerror pop up alert message should be displayed","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1734654898694,"stop":1734654898697}],"attachments":[],"parameters":[{"name":"code","value":"Invalid code2"},{"name":"alert","value":"syntaxerror pop up alert message"}],"start":1734654891063,"stop":1734654899492}